spring.application.name=ms-calendario
server.port=8085

app.calendar.service-account-key-location=${CALENDAR_SERVICE_ACCOUNT_KEY:classpath:service-account-key.json}
app.calendar.application-name=Innovatech-Calendar
app.calendar.id=${CALENDAR_ID:2585bf09e2dc7d66196f995049ecda62942cede8f7458e033e49b28d76b56ea1@group.calendar.google.com}
app.calendar.timezone=${CALENDAR_TIMEZONE:America/Santiago}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://bd-fullstackiii.cfuwvo6zjkhz.us-east-1.rds.amazonaws.com:5432/BDfullsckIII}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pablo123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
