spring.application.name=ms-proyectos

app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:K9m@T2x#P8v$R4q!W7z^F1n&L5y*H3u_B6c%D9e}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://bd-fullstackiii.cfuwvo6zjkhz.us-east-1.rds.amazonaws.com:5432/BDfullsckIII}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pablo123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8082
